### ISSUE TITLE
No drop down animation on wayland

### ISSUE THREAD

**Issue by ernesto1** [zzrough/gs-extensions-drop-down-terminal#180] opened 2017-04-16 23:34 UTC
For some reason the drop down animation does not work **under wayland**.  Instead I get a different animation where the terminal seems to "grow" from within the center of the screen until it covers the specified terminal size.  This happens rather quickly.

This behaviour is exhibited with the animation turned on or off.

If I use **X** as the display server the **animation works** properly.  If I disable it, the terminal just appears as it should.

The problem is experienced on fedora 25.  No nvidia drivers installed.

**Comment by zzrough** [comment] 2017-04-18 07:32
Duplicate of #171, closing

**Closed by zzrough** 2017-04-18 07:32 UTC
