### ISSUE TITLE
Terminal drops down relative to top window on Gnome 3.18.1

### ISSUE THREAD

**Issue by imnotjames** [zzrough/gs-extensions-drop-down-terminal#117] opened 2015-10-18 06:16 UTC
The drop down terminal seems to be positioned relative to the top window that is focused before it is opened.

![screenshot from 2015-10-18 01-57-32](https://cloud.githubusercontent.com/assets/1551593/10562820/81ff0562-753d-11e5-91aa-9dc1a33738c9.jpg)

The top-most window is lined in red underneath the terminal.

This seems to be for any window.  This is the latest version of the extension, from git.  I have tried restarting gnome and turning off and on the extension.  This did not occur on 3.16 and only started being an issue with 3.18.1.  I have turned off all other extensions.

When I change the window type from being a `Gdk.WindowTypeHint.DROPDOWN_MENU` to being a `Gdk.WindowTypeHint.DOCK` it seems to correct the issue with some minor tweaks required to get the positiong correct but I'm not sure what repurcussions that may have.  It also seems to make the animations work correctly instead of the zooming in animation.  I'll experiment with some of the other type hints and see if any could also correct this - if it's fine then I could open a pull request with this change.  See: imnotjames/gs-extensions-drop-down-terminal@f71b84a83c39a0f6c7feaa95950f0642f04a7d30

I've also found that I can sort of correct this by calling `DropDownTerminalExtension._updateWindowGeometry` after `DropDownTerminalExtension._bus.FocusRemote` is called.. but I think that's masking the issue rather than correcting it.

I was thinking that this could be caused by the drop down terminal parenting to the top-most window somehow. Then gnome shell could decide that since it's a dropdown-menu and it has a parent that it MUST be near the top window.  However, I'm not sure if you could fix that with a hack to `set_transient_for` or `set_attached_to` to the root window?  I don't even know if that's possible.  I'm not really great with GTK.

**Comment by fmoralesc** [comment] 2015-10-18 08:08
`Gdk.WindowTypeHint.UTILITY` seems to work.

**Comment by imnotjames** [comment] 2015-10-18 09:09
`Gdk.WindowTypeHint.Normal` works - and that's how Guake and Tilda operate.  However, it does leave the zoom in animation that the other issue seems to cover.

**Comment by fmoralesc** [comment] 2015-10-18 09:31
The issue I had with `DOCK` was that it opened the terminal behind the top bar.

**Comment by imnotjames** [comment] 2015-10-18 15:33
Even when you removed the subtraction of the panel height from the geometry setting per imnotjames/gs-extensions-drop-down-terminal@f71b84a line 454?

**Comment by fmoralesc** [comment] 2015-10-18 16:33
Ah, no I didn't do that, I wasn't working on top of your patch. I can confirm that doing it `DOCK` works fine.

**Comment by imnotjames** [comment] 2015-10-20 02:26
Opened a pull request with that change

**Comment by guillermohs9** [comment] 2015-10-23 18:43
Hi everyone, I'm using gnome 3.18.1 on Arch and cannot switch this extension on since last update a couple of weeks ago, and on the gnome website it is marked as outdated, any clues on this issue? I love this terminal!

**Closed** 2015-11-04 20:58 UTC
