### ISSUE TITLE
Display issues with gnome-shell 3.18.0

### ISSUE THREAD

**Issue by richionizor** [zzrough/gs-extensions-drop-down-terminal#115] opened 2015-10-08 13:16 UTC
There are two problems with this extension with GNOME Shell 3.18.0:
* The terminal always takes 100% of the screen space
* The terminal does not drop down but rather animates from the center of the screen

This might be quite early, since the current GNOME was released just weeks ago. However, I love this extension and would very much like to continue using it :)

**Comment by zzrough** [comment] 2015-10-08 13:20
I saw the second one (strange animation) but this is not critical. I'm so used to this terminal I preferred to release. Did not see the first problem though.

**Comment by Saren-Arterius** [comment] 2015-10-09 04:54
I have tried git version and https://extensions.gnome.org/extension/442/drop-down-terminal/
The extensions.gnome.org version looks better and it doesn't position itself in center, unlike git version.

**Comment by eigoor** [comment] 2015-10-09 07:59
I am using multiple monitors and the terminal always opens on the screen with my mouse and not on the primary screen.

**Comment by zzrough** [comment] 2015-10-09 08:06
@Saren-Arterius This is exactly the same version, did you restart the shell *and* the extension? (you must either log out and log in or disable/enable the extension -- as the terminal is kept open in case of a gnome-shell crash)

@eigoor Is this a regression in 3.18? I think it has already been reported before...

**Comment by Wabuo** [comment] 2015-10-09 09:43
I also have the second one on 3.18 on Arch with the git version ...
>* The terminal does not drop down but rather animates from the center of the screen

**Comment by eigoor** [comment] 2015-10-09 09:48
I did not notice this in 3.16. It started happening today after updating to 3.18.

**Comment by Saren-Arterius** [comment] 2015-10-09 09:48
Well I am using Arch too

**Comment by ddulic** [comment] 2015-10-09 11:19
> I did not notice this in 3.16. It started happening today after updating to 3.18.

Getting the same problem ever since I updated to 3.18. Also using Arch.

**Comment by Wabuo** [comment] 2015-10-11 16:29
Yey; I figured out that the “jumpiness” if it will display correct at the bottom or some ware between depends on if there is a window under it and where it is ...

**Comment by opensamba** [comment] 2015-10-11 23:16
I confirm I have the same issue with latest version

To reproduce you just need to open transmission-gtk and then drop down the term menu.
My terminal is change automatically the position in the middle of the screen, instead to be fixed at the top.

**Comment by fmoralesc** [comment] 2015-10-17 10:35
Changing line 319 in terminal.js to

~~~ js
        let window = new Gtk.Window({type : Gtk.WindowType.POPUP});
~~~

seems to fix the issue for me.

**Comment by opensamba** [comment] 2015-10-17 21:05
change proposed by @fmoralesc  doesn't work for me.

If I restart gnome-shell and I try to open another app I can't get the focus of the drop-down-terminal anymore.

I need stop gnome, rollback the 319 line and start again.

**Comment by opensamba** [comment] 2015-10-17 21:06
anyway this fix the windows_moving issue

**Comment by richionizor** [comment] 2015-10-17 21:16
Same here: The change of @fmoralesc fixes the window animation but makes the terminal unusable, since it can't be focused anymore.

**Comment by fmoralesc** [comment] 2015-10-17 21:41
Maybe this has to do with the mutter/gnome-shell version you guys are using? I don't have the focus issue with 3.18.1.

**Comment by imnotjames** [comment] 2015-10-18 06:23
@opensamba I think I am experiencing what you're describing.  I opened a new issue since it seems to be distinct from the original issue this thread was for - #117

**Comment by eldelacajita** [comment] 2015-10-26 20:45
Same issues here on Gnome 3.18. It opens with a scaling animation from the center and then closes correctly, sliding upwards. Also, it jumps to the top of the active window.

**Comment by zzrough** [comment] 2015-11-04 21:16
@opensamba does this works with latest master, where the type is COMBO?

**Comment by opensamba** [comment] 2015-11-06 10:27
Hi @zzrough ,
I'm sorry but this is still not working properly.
I was testing this yesterday with transmission opened and the drop-down-terminal 
and I took a screenshot:

http://i.imgur.com/W33H3os.png

I updated to the latest version, using this aur here, which use the latest version available on the git repo:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=gnome-shell-extension-drop-down-terminal-git

I notice this happen to several gnome application which use gtk-3.
Hope this info can be useful for you.

bye

**Comment by zzrough** [comment] 2015-11-06 10:52
@opensamba Weird, I'm on Fedora with transmission-gtk-2.84-8 and I can't reproduce the window jump that I had from time to time ? I also have mutter-3.18.1-4, gnome-shell-3.18.1-1 and gtk3-3.18.2-1. I don't see any additional patch in gtk3 though...

**Comment by TonicArtos** [comment] 2015-11-16 23:46
I've noticed that lately WMs seem to be more aggressive about overriding window placement. GTK documentation indicates the correct hint to force window placement is to set the window type to DOCK.

As it is, I currently have a branch and pull request for another feature that implements the dock window type and that may just fix this problem, #122.

**Comment by eldelacajita** [comment] 2015-11-20 17:37
I updated recently and it's fixed for me now. Thanks!

**Comment by zzrough** [comment] 2015-11-25 21:30
I've merged @TonicArtos changes into master, the issue is fixed.

**Closed by zzrough** 2015-11-25 21:30 UTC
