### ISSUE TITLE
Broken on GNOME 3.22

### ISSUE THREAD

**Issue by ukch** [zzrough/gs-extensions-drop-down-terminal#164] opened 2016-10-04 09:37 UTC
After upgrading to GNOME 3.22, my drop-down terminal was re-enabled (it has been disabled since 3.20). However, trying to start the terminal using `ctrl-`` results in the error message 'Drop down terminal ended abruptly'.
The message then suggests I enable debugging, but I can't see a way to do that.

GNOME Shell version: 3.22.0
Dropdown terminal version: 18

**Comment by sdt-ork** [comment] 2016-10-04 09:39
You should have the errors available in the systemd journal (using journalctl | grep -i drop or something like that). Before it used to be in xsession error logs or similar.

**Comment by ukch** [comment] 2016-10-04 12:58
`journalctl` output:

```
Oct 04 10:23:31 abijah gjs[4968]: JS ERROR: Gtk.CssProviderError: gtk.css:32:10not a number
                                  DropDownTerminal<._init@/home/joel/.local/share/gnome-shell/extensions/drop-down-terminal@gs-extensions.zzrough.org/terminal.js:147
                                  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
                                  _Base.prototype._construct@resource:///org/gnome/gjs/modules/lang.js:110
                                  Class.prototype._construct/newClass@resource:///org/gnome/gjs/modules/lang.js:213
                                  @/home/joel/.local/share/gnome-shell/extensions/drop-down-terminal@gs-extensions.zzrough.org/terminal.js:592
```

**Comment by SvetlinZarev** [comment] 2016-10-10 20:42
The error on my side: 
```

Oct 10 23:26:52 deepspace gnome-software-service.desktop[2041]: 20:26:52:0845 Gs  no app for changed drop-down-terminal@gs-extensions.zzrough.org
                                      DropDownTerminal<._init@/home/svetlin/.local/share/gnome-shell/extensions/drop-down-terminal@gs-extensions.zzrough.org/terminal.js:153
                                      @/home/svetlin/.local/share/gnome-shell/extensions/drop-down-terminal@gs-extensions.zzrough.org/terminal.js:631
Oct 10 23:32:05 deepspace gnome-shell[1903]: JS LOG: error: Drop Down Terminal ended abruptly: You can activate the debug mode to nail down the issue
                                      DropDownTerminal<._init@/home/svetlin/.local/share/gnome-shell/extensions/drop-down-terminal@gs-extensions.zzrough.org/terminal.js:153
                                      @/home/svetlin/.local/share/gnome-shell/extensions/drop-down-terminal@gs-extensions.zzrough.org/terminal.js:631
Oct 10 23:33:38 deepspace gnome-shell[1903]: JS LOG: error: Drop Down Terminal ended abruptly: You can activate the debug mode to nail down the issue
```
But it's pretty interesting that after I removed the whole content of gtk.css and opened the drop down terminal it worked. Then I restored gtk.css as it was in order to track down which line was causing the issue, but it was still working. So I cannot reproduce it anymore but my setup is in the same state as when it was not working.

**Comment by ehuisman** [comment] 2016-10-13 12:57
This issue was actually fixed in d80b883. It just seems that the version on http://extensions.gnome.org is too old to include the fix.

**Comment by gigi199596** [comment] 2016-10-19 19:38
Same issue...

Someone has a solution?

**Comment by ehuisman** [comment] 2016-10-19 21:14
Well, you can download a ZIP archive directly from GitHub and move the `drop-down-terminal@gs-extensions.zzrough.org` folder to `~/.local/share/gnome-shell/extensions`.

**Comment by zzrough** [comment] 2016-10-19 21:47
I'm late to reply again...

weird, I just downloaded from extensions.gnome.org at https://extensions.gnome.org/download-extension/drop-down-terminal@gs-extensions.zzrough.org.shell-extension.zip?version_tag=6131 and the archive is correct with the fix in d80b883

@ukch could you copy/paste the CSS you have in ```~/.local/share/gnome-shell/extensions/drop-down-terminal@gs-extensions.zzrough.org/gtk.css``` please? Just to be sure the fix is missing?

The version do not list 3.22 has supported, but this is not required anymore.

**Comment by mmontanozenoss** [comment] 2016-11-27 05:51
Thank you guys!, it works with the fix on d80b883. You can Download from here: https://extensions.gnome.org/download-extension/drop-down-terminal@gs-extensions.zzrough.org.shell-extension.zip?version_tag=6131 as zzrough says.

Good job with this extension.

**Comment by jakubmadej** [comment] 2016-12-07 19:01
Same issue here. Problem is that I can't install from zip file you provide. I get "incorrect extension" (exact message can be different as I'm translating now from my native language).

**Comment by zzrough** [comment] 2017-01-23 19:30
Mmmh I totally failed to release for 3.22 for the first time. I've uploaded support for 3.22 from the PR https://github.com/zzrough/gs-extensions-drop-down-terminal/pull/173 a couple of minutes ago. Should be available in the next 24h.

**Closed by zzrough** 2017-01-23 19:30 UTC
