### ISSUE TITLE
Support for multiple tabs

### ISSUE THREAD

**Issue by pfeldman** [zzrough/gs-extensions-drop-down-terminal#221] opened 2018-09-29 13:50 UTC
It would be nice to be able to start new tabs with different instances of a terminal, and add hotkeys to navigate through them. Please refer [yakuake](https://www.kde.org/applications/system/yakuake/)

**Comment by zzrough** [comment] 2018-10-01 14:48
Duplicate of #150 which already is a PR for that.

**Closed by zzrough** 2018-10-01 14:48 UTC
