### ISSUE TITLE
Animation no longer works on Ubuntu 18.04

### ISSUE THREAD

**Issue by Cerberus97** [zzrough/gs-extensions-drop-down-terminal#209] opened 2018-05-02 18:48 UTC
The drop down animation no longer works. Regardless of whether the "Animation" checkbox is checked, the terminal animation is now a fade in and enlarge, instead of the earlier drop down animation.

Edit: This issue is only present if Wayland is used, the animation works fine in Xorg

**Comment by frol** [comment] 2018-05-26 08:48
This is a duplicate of #163 and #171.

**Closed** 2018-05-26 10:27 UTC
